[DQ_py.cpp] Added the methods Q4 and Q8.
dqrobotics/python pull request #45
Opened 2023-02-23 06:33 UTC by juanjqo

@dqrobotics/developers 

Hi @mmmarinho, 

This PR adds the bindings for the methods Q4 and Q8, which were recently added in C++ in [this PR](https://github.com/dqrobotics/cpp/pull/56) by Marcos. I added the tests [here](https://github.com/dqrobotics/python-tests/pull/6). 

Best regards, 

Juancho

![](https://img.shields.io/badge/Tests-developer%20workflow-orange)![](https://img.shields.io/badge/Ubuntu%2020.04.5%20LTS%20(x64)-passing-passing)

2023-02-27 13:51 UTC, mmmarinho requested changes
@juanjqo 
Nothing major.

2023-02-27 13:51 UTC, mmmarinho commented on src/DQ_py.cpp
> +    dq.def("Q8"                  ,&DQ::Q8,                    "Retrieves the partial derivative of a DQ with respect to its logarithm.");
a unit DQ?

2023-02-27 13:51 UTC, mmmarinho commented on src/DQ_py.cpp
> +    m.def("Q8"                  ,&DQ_robotics::Q8,                   "Retrieves the partial derivative of a DQ with respect to its logarithm.");
a unit DQ?

2023-04-06 11:14 UTC, juanjqo commented on src/DQ_py.cpp
> +    dq.def("Q8"                  ,&DQ::Q8,                    "Retrieves the partial derivative of a DQ with respect to its logarithm.");
@mmmarinho fixed!

2023-04-06 11:14 UTC, juanjqo commented on src/DQ_py.cpp
> +    m.def("Q8"                  ,&DQ_robotics::Q8,                   "Retrieves the partial derivative of a DQ with respect to its logarithm.");
@mmmarinho fixed!

2023-04-22 07:31 UTC, mmmarinho approved these changes

2023-04-22 07:31 UTC, merged